version: '3'

services:
  #  start MariaDB, and ensure that data is stored to a mounted volume
  mariadb:
    image: 'mariadb:10.6'
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: AbsensiService
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: password

    volumes:
      - ./db-data/mariadb:/docker-entrypoint-initdb.d
      - ./my.cnf:/etc/mysql/conf.d/my.cnf

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: mariadb
      # PMA_USER: root
      # PMA_PASSWORD: password
    ports:
      - "8090:80"

  meilisearch:
    container_name: meilisearch_AbsensiService
    image: getmeili/meilisearch:v0.29
    environment:
      - http_proxy
      - https_proxy
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-masterKey}
      - MEILI_NO_ANALYTICS=${MEILI_NO_ANALYTICS:-true}
      - MEILI_ENV=${MEILI_ENV:-development}
      - MEILI_LOG_LEVEL
      - MEILI_DB_PATH=${MEILI_DB_PATH:-/data.ms}
    ports:
      - ${MEILI_PORT:-7700}:7700
    # networks:
    #   - meilisearch
    volumes:
      - ./data.ms:/data.ms
    restart: unless-stopped

  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always

  api-scantime:
    image: hello/api-scantime
    ports:
      - "8082:8080"
    restart: always